spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hiredb
    username: hireuser
    password: vurtagan
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true

logging:
  level:
    root: warn
    org.hibernate: debug
    org.springframework.web: debug

